"optimizer_instances":
  "1":
    "optimizer": "SMAC_Optimizer"
    "hyperparameters": {"xi": 0.01}
  "2":
    "optimizer": "SMAC_BO"
    "hyperparameters": {"xi": 0.01}
  "3":
    "optimizer": "OptunaOptimizer"
    "hyperparameters": {"sampler": "TPE"}
  "4":
    "optimizer": "SyneTune_KDE"
    "hyperparameters": {}